CREATE TABLE tbl_Employee(
[ID] INT IDENTITY(1,1) NOT NULL,
[Username] NVARCHAR (50) NOT NULL,
[Gender] INT NOT NULL,
[Phone] VARCHAR(15) NOT NULL,
[Email] NVARCHAR(100) NULL,
[DOB] DATE NOT NULL,
[Address] NVARCHAR(300) NOT NULL, 
[Document] INT NOT NULL,
[SSC] BIT DEFAULT 0,
[Inter] BIT DEFAULT 0,
[Degree] BIT DEFAULT 0,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)ON [PRIMARY]
)
CREATE TABLE tbl_Gender(
[ID] INT IDENTITY(1,1) NOT NULL,
[Code] INT NOT NULL,
[Value] VARCHAR(15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)ON [PRIMARY]
)

CREATE TABLE tbl_Document(
[ID] INT IDENTITY(1,1) NOT NULL,
[Code] INT NOT NULL,
[Value] VARCHAR(15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)ON [PRIMARY]
)

